// //Created by Jon Tyson : jtyson3@gatech.edu
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public enum UnitName
{
	Infantry,
	Stinger,
	Stryker,
	CarpetBomber,
	TacticalFighter,
	Interceptor,
	AttackCopter,
	LiftCopter,
	LightTank,
	MediumTank,
	Rockets,
	Missiles,
	FieldArtillery,
	Mortar,
	SupplyTank,
	UAV,
	Humvee,
	Sniper,
	MobileRadar,
	Corvette,
	Destroyer,
	Submarine,
	Carrier,
	Amphibious,
	SupplyShip,
	AATank,
	Boomer,
	Headquarters,
	City,
	Factory,
	Airport,
	Shipyard,
	ComTower,
	Bridge,
	Bunker}
;
public enum UnitState
{
	UnMoved,
	BuildingBridge,
	Selected,
	Moving,
	AwaitingOrder,
	TargetingUnit,
	Unloading,
	FinishedMove,
	Dying}
;
public enum UnitOrderOptions
{
	ProduceMissile,
	BuildBridge,
	Attack,
	Supply,
	Repair,
	Capture,
	Load,
	Unload,
	Board,
	AddGeneral,
	GeneralPower,
	BuildUnit,
	UnStealthify,
	Stealthify,
	Join,
	EndTurn}
;
public enum MovementType
{
	Air,
	Sea,
	Littoral,
	LightVehicle,
	HeavyVehicle,
	Tank,
	Amphibious,
	Sniper,
	Infantry}
;
//Story idea: in the middle of and right after nuclear war
public enum UnitRanks
{
	UnRanked,
	Private,
	Corporal,
	Sergeant,
	Elite}
;
//Used for determining counterattack ability
public enum UnitAttackType
{
	Direct,
	Indirect,
	Both}
;
public enum Generals
{
	Lucy, //General boost, after lucille ball
	Navya, //Boosted ground units, female Indian
	Desmond, //Boosted naval units
	Taron, //Boosted air units
	Kiera //Heals units in zone, ex nurse
}
public enum AILevel
{
	Human,
	Easy,
	Medium,
	Hard}
;
public enum WeatherType
{
	Clear,
	Snowing,
	ThunderStorm,
	Dusty,
	NuclearFallout/*Has decent probability of causing 1 damage to all units on map each day*/}
;
public enum BLOCKDIRECTIONS
{
	West,
	East,
	North,
	South}
;
public enum TERRAINTYPE
{
	River,
	Mountain,
	Sea,
	Shoal,
	Road,
	Forest,
	Hill,
	Plain}
;