// //Created by Jon Tyson : jtyson3@gatech.edu
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public class GameSettings
{
	public int propertyBaseFunds;
	public int startingFunds;
	public bool fogOfWarEnabled, randomWeather;
	public WeatherType selectedWeather;
	public GameSettings()
	{
		propertyBaseFunds = 1000;
		selectedWeather = WeatherType.Clear;
	}
}