// //Created by Jon Tyson : jtyson3@gatech.edu
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
/// <summary>
/// Defines production rules for maps with factories and shipyards only
/// </summary>
public class GroundNavalProduction
{
	public GroundNavalProduction ()
	{
	}
	
	public List<ProductionEngine.ProductionRule> GetRules ()
	{
		List<ProductionEngine.ProductionRule> rules = new List<ProductionEngine.ProductionRule> ();
		rules.Add (SupplyShipRule);
		rules.Add (OverallForceRule);
		return rules;
	}
	/// <summary>
	/// When to build supply ships for transporting units
	/// </summary>
	/// <returns>The ground rule.</returns>
	/// <param name="data">Data.</param>
	/// <param name="thisPlayer">This player.</param>
	List<Tuple<UnitName, float>> SupplyShipRule (Instance data, Player thisPlayer)
	{
		List<Tuple<UnitName, float>> outList = new List<Tuple<UnitName, float>> ();
		if (data.playerUnitCount [(int)UnitName.SupplyShip] < 2) {
			outList.Add (new Tuple<UnitName, float> (UnitName.SupplyShip, .25f));
			// Suppress expensive ground unit production
			outList.Add (new Tuple<UnitName, float> (UnitName.MediumTank, -.2f));
			outList.Add (new Tuple<UnitName, float> (UnitName.Rockets, -.2f));
			outList.Add (new Tuple<UnitName, float> (UnitName.LightTank, -.2f));
		}
		return outList;
	}
	/// <summary>
	/// A rule that builds more navy when the enemy has more navy, 
	/// and more ground when the enemy has more ground troops
	/// </summary>
	/// <returns>The force rule.</returns>
	/// <param name="data">Data.</param>
	/// <param name="thisPlayer">This player.</param>
	List<Tuple<UnitName, float>> OverallForceRule (Instance data, Player thisPlayer)
	{
		var outList = new List<Tuple<UnitName, float>> ();
		var totalEnemyGround = data.GetEnemyOffensiveVehicleUnitCount ();
		var totalEnemyNavy = data.GetEnemyNavalUnitCount ();
		var totalPlayerGround = data.GetPlayerOffensiveVehicleUnitCount ();
		var totalPlayerNavy = data.GetPlayerNavalUnitCount ();
		
		if (totalEnemyNavy > totalEnemyGround) {
			if (totalPlayerNavy > totalPlayerGround) {
				outList.Add (new Tuple<UnitName, float> (UnitName.Corvette, .1f));
				outList.Add (new Tuple<UnitName, float> (UnitName.Destroyer, .1f));
				outList.Add (new Tuple<UnitName, float> (UnitName.Submarine, .1f));
			} else {
				outList.Add (new Tuple<UnitName, float> (UnitName.Corvette, .15f));
				outList.Add (new Tuple<UnitName, float> (UnitName.Destroyer, .15f));
				outList.Add (new Tuple<UnitName, float> (UnitName.Submarine, .15f));
				outList.Add (new Tuple<UnitName, float> (UnitName.Boomer, .1f));
				outList.Add (new Tuple<UnitName, float> (UnitName.FieldArtillery, -.1f));
				outList.Add (new Tuple<UnitName, float> (UnitName.LightTank, -.1f));
				outList.Add (new Tuple<UnitName, float> (UnitName.MediumTank, -.1f));
			}
		} else {
			if (totalPlayerNavy > totalPlayerGround) {
				outList.Add (new Tuple<UnitName, float> (UnitName.FieldArtillery, .1f));
				outList.Add (new Tuple<UnitName, float> (UnitName.LightTank, .1f));
				outList.Add (new Tuple<UnitName, float> (UnitName.MediumTank, .1f));
				outList.Add (new Tuple<UnitName, float> (UnitName.Rockets, .1f));
			} else {
				// Do nothing
			}
		}
		return outList;
	}
}
