// //Created by Jon Tyson : jtyson3@gatech.edu
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


public class TooltipData : MonoBehaviour
{
	public string mouseOverText;
	public void SetText (string inText)
	{
		mouseOverText = inText;
	}
	public string GetText ()
	{
		return mouseOverText;
	}
}
