// //Created by Jon Tyson : jtyson3@gatech.edu
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class UnitTarget
{
	public AttackableObject primaryTarget{ get; private set; }
	public TerrainBlock targetBlock{ get; private set; }
	public bool canReachBlock{ get; private set; }
	UnitController parent{ get; set; }
	public UnitTarget (UnitController parent, AttackableObject target =  null)
	{
		this.parent = parent;
		SetTarget (target);
	}
	public void SetTarget (AttackableObject newTarget)
	{
		if (newTarget != null) {
			//InGameController.instance.currentTerrain(parent.currentBlock, newTarget.GetOccupyingBlock(), parent, 1);
		}
	}
}

